#===============================================================================$
#   __          __   _ _      _         _   _            _____           _      #
#   \ \        / /  | | |    (_)       | | | |          |  __ \         | |     #
#    \ \  /\  / /_ _| | | __  _ _ __   | |_| |__   ___  | |__) |_ _ _ __| | __  #
#     \ \/  \/ / _` | | |/ / | | '_ \  | __| '_ \ / _ \ |  ___/ _` | '__| |/ /  #
#      \  /\  / (_| | |   <  | | | | | | |_| | | |  __/ | |  | (_| | |  |   <   #
#       \/  \/ \__,_|_|_|\_\ |_|_| |_|  \__|_| |_|\___| |_|   \__,_|_|  |_|\_\  #
#                                                                               #
#===============================================================================#
##                       //  FORKED by Mr_were  //                             ##
#===============================================================================#
#                                                                               #
#                        (c) Efnilite 2020-2021                                 #
#                                                                               #
#===============================================================================#

# Enable metrics
# Metrics is for collecting anonymous server data (about the plugin)
metrics: true

# Verbosing
# If this is set to true it will display extra data when stuff happens (useful for developers)
verbose: false

# Options about Bungeecord/autojoining
bungeecord:

    # Enabling this will make players who join the server (that's running this plugin) automatically join the game on that server
    # !! If this is disabled, you have to use /witp join to join and /witp leave to leave. !!
    enabled: false

    # The server the players will be returned to after the game is done
    return_server: Lobby

world:
    # The world in which the personal parkours will take place
    name: witp

    # The world players will be teleported to if they accidentally join the WITP world without being a player
    fall-back: world

# Options for the option menu
options:

    # If options are enabled
    enabled: true

    # The item
    item: feather

    # Enables/disables the inventory handling system
    inventory-handling: true

# The different styles players can select
styles:

    # If styles are enabled
    enabled: true

    # The default style
    default: green

    # The list of all available styles, which you can add to if you want
    list:
        red: [red_wool, red_stained_glass, red_concrete, red_terracotta]
        blue: [blue_wool, blue_stained_glass, blue_concrete, blue_terracotta]
        light blue: [light_blue_wool, light_blue_stained_glass, light_blue_concrete, light_blue_terracotta]
        green: [green_wool, green_stained_glass, green_concrete, green_terracotta]
        lime: [lime_wool, lime_stained_glass, lime_concrete, lime_terracotta]
        cyan: [cyan_wool, cyan_stained_glass, cyan_concrete, cyan_terracotta]
        purple: [purple_wool, purple_stained_glass, purple_concrete, purple_terracotta]
        yellow: [yellow_wool, yellow_stained_glass, yellow_concrete, yellow_terracotta]
        gray: [gray_wool, gray_stained_glass, gray_concrete, gray_terracotta]
        end: [end_stone, end_stone_bricks, purpur_block, purpur_pillar]
        nether: [netherrack, nether_bricks, red_nether_bricks, chiseled_nether_bricks, nether_wart_block, nether_gold_ore, netherite_block, basalt]
        quartz: [smooth_quartz, chiseled_quartz_block, quartz_block, quartz_bricks, quartz_pillar]
        ocean: [prismarine, prismarine_bricks, dark_prismarine, sea_lantern]
        redstone: [observer, dispenser, redstone_block, piston, sticky_piston, redstone_lamp, target]
        overworld: [grass_block, stone, cobblestone, oak_log]
        ores: [diamond_ore, gold_ore, iron_ore, coal_ore, nether_gold_ore, lapis_ore, redstone_ore, emerald_ore, nether_quartz_ore]
        wood: [oak_planks, spruce_planks, jungle_planks, acacia_planks, birch_planks, dark_oak_planks, oak_log, spruce_log, jungle_log, birch_log, acacia_log, dark_oak_log]

# How the scoreboard looks
# Placeholders: %score%, %time%
scoreboard:
    enabled: true

    title: '&cWITP &7&o(forked)'
    lines:
        - '&a'
        - '&7Score: &f%score%'
        - '&7Time: &f%time%'
        - '&b'
        - '&6&lamazing server'

# Options for the messages
# %p is the player.
messages:

    # If join/leave messages should be shown
    join-leave-enabled: true
    join: '&7%p has joined the server.'
    leave: '&7%p has left the server.'

    divider: '&7----------------------------------------'
    score: '&aYour score: &f%s'
    time: '&aYour time: &f%s'
    highscore: '&aYour highscore: &f%s'
    message:
        miss: '&7You missed your high score by %s points!'
        beat: '&7You beat your high score by %s points!'
        tied: '&7You tied your high score!'

# Options for custom rewards
rewards:

    # If rewards are enabled
    enabled: true

    # The interval at which they get a reward
    # (so for every 50 blocks the player jumps, they get a reward)
    # (this means doing a run of 27 and 23 will still get you coins even though you haven't had a score of 50)
    interval: 69

    # The command that will be executed if the interval is met
    # 'null' means no command
    # FORK: now supports %PLAYER% placeholder
    command: 'msg %PLAYER% You have jumped total of 69 blocks, congratulations!'

    # The amount of money players will receive as Vault currency
    vault-reward: 0

    # The message you get after the interval is met
    # 'null' means no message
    message: '&2+ ¥0'

# Options for more specific rewards, added by a FORK - no official support
moarrewards:
    # Is this section enabled?
    enabled: true

    # The specific interval at which we execute command
    # (so if player reaches 150 blocks he'll get 300 money, and if 200 blocks he's gonna get 800 money)
    # Separate using ;;
    intervals:
        25: "execute at %PLAYER% run summon firework_rocket ~1 ~-3 ~ {LifeTime:25,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Flight:1,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;3887386,2651799,14602026,6719955],FadeColors:[I;11743532,3887386,8073150,2651799,6719955]}]}}}}"
        50: "execute at %PLAYER% run summon firework_rocket ~1 ~-3 ~ {LifeTime:25,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Flight:1,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;3887386,2651799,14602026,6719955],FadeColors:[I;11743532,3887386,8073150,2651799,6719955]}]}}}}"
        75: "execute at %PLAYER% run summon firework_rocket ~1 ~-3 ~ {LifeTime:25,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Flight:1,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;3887386,2651799,14602026,6719955],FadeColors:[I;11743532,3887386,8073150,2651799,6719955]}]}}}}"
        100: "execute at %PLAYER% run summon firework_rocket ~1 ~-3 ~ {LifeTime:25,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Flight:1,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;3887386,2651799,14602026,6719955],FadeColors:[I;11743532,3887386,8073150,2651799,6719955]}]}}}}"
        125: "execute at %PLAYER% run summon firework_rocket ~1 ~-3 ~ {LifeTime:25,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Flight:1,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;3887386,2651799,14602026,6719955],FadeColors:[I;11743532,3887386,8073150,2651799,6719955]}]}}}}"
        150: "money give %PLAYER% 300;; msg %player% Congrats, you've jumped 150 blocks!"
        200: "execute at %PLAYER% run summon firework_rocket ~1 ~-3 ~ {LifeTime:25,FireworksItem:{id:firework_rocket,Count:1,tag:{Fireworks:{Flight:1,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;3887386,2651799,14602026,6719955],FadeColors:[I;11743532,3887386,8073150,2651799,6719955]}]}}}}"

# Options for particles/sounds
particles:

    # The particle type
    # Use this list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html or else it won't work
    particle-type: 'SPELL_INSTANT'

    # The sound type
    # Use this list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html or else it won't work
    sound-type: 'BLOCK_NOTE_BLOCK_GUITAR'

    # The pitch of the sound
    sound-pitch: 3